apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: optimus

resources:
  - environment.yaml
  - decision_model.yaml
  - integrations.yaml
  - knowledge_source.yaml
  - policy.yaml
