run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - revive
    - gofmt

linters-settings:
  revive:
    rules:
      - name: exported
        disabled: true
      - name: package-comments
        disabled: true

issues:
  exclude-dirs:
    - vendor
    - bin
