apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: optimus

resources:
  - ../../base/postgres
  - ../../base/redpanda
  - ../../base/temporal
  - ../../base/kong
  - ../../base/ollaya
  - ../../base/observability
