// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

type Asset struct {
	ID        string             `json:"id"`
	TenantID  string             `json:"tenant_id"`
	Name      string             `json:"name"`
	AssetType string             `json:"asset_type"`
	Plant     string             `json:"plant"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Document struct {
	ID        string             `json:"id"`
	TenantID  string             `json:"tenant_id"`
	Title     string             `json:"title"`
	DocType   string             `json:"doc_type"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type DocumentChunk struct {
	ID         int64              `json:"id"`
	TenantID   string             `json:"tenant_id"`
	DocumentID string             `json:"document_id"`
	ChunkIndex int32              `json:"chunk_index"`
	Content    string             `json:"content"`
	Tsv        interface{}        `json:"tsv"`
	Embedding  pgvector.Vector    `json:"embedding"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Outbox struct {
	ID            int64              `json:"id"`
	TenantID      string             `json:"tenant_id"`
	EventType     string             `json:"event_type"`
	CorrelationID string             `json:"correlation_id"`
	Traceparent   pgtype.Text        `json:"traceparent"`
	Payload       []byte             `json:"payload"`
	PublishedAt   pgtype.Timestamptz `json:"published_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type Signal struct {
	ID         string             `json:"id"`
	TenantID   string             `json:"tenant_id"`
	AssetID    string             `json:"asset_id"`
	Symptom    string             `json:"symptom"`
	Status     string             `json:"status"`
	WorkflowID pgtype.Text        `json:"workflow_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Tenant struct {
	ID        string             `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type WorkOrder struct {
	ID             string             `json:"id"`
	TenantID       string             `json:"tenant_id"`
	AssetID        string             `json:"asset_id"`
	Priority       string             `json:"priority"`
	Status         string             `json:"status"`
	IdempotencyKey string             `json:"idempotency_key"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}
