// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	GetSignal(ctx context.Context, arg GetSignalParams) (Signal, error)
	GetUnpublishedOutboxMessages(ctx context.Context, limit int32) ([]GetUnpublishedOutboxMessagesRow, error)
	GetWorkOrder(ctx context.Context, arg GetWorkOrderParams) (WorkOrder, error)
	MarkOutboxMessagePublished(ctx context.Context, arg MarkOutboxMessagePublishedParams) error
	SaveOutboxMessage(ctx context.Context, arg SaveOutboxMessageParams) (int64, error)
	SaveSignal(ctx context.Context, arg SaveSignalParams) error
	SaveWorkOrder(ctx context.Context, arg SaveWorkOrderParams) error
}

var _ Querier = (*Queries)(nil)
