// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: signals.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSignal = `-- name: GetSignal :one
SELECT id, tenant_id, asset_id, symptom, status, workflow_id, created_at
FROM signals
WHERE tenant_id = $1 AND id = $2
`

type GetSignalParams struct {
	TenantID string `json:"tenant_id"`
	ID       string `json:"id"`
}

func (q *Queries) GetSignal(ctx context.Context, arg GetSignalParams) (Signal, error) {
	row := q.db.QueryRow(ctx, getSignal, arg.TenantID, arg.ID)
	var i Signal
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AssetID,
		&i.Symptom,
		&i.Status,
		&i.WorkflowID,
		&i.CreatedAt,
	)
	return i, err
}

const saveSignal = `-- name: SaveSignal :exec
INSERT INTO signals (id, tenant_id, asset_id, symptom, status, workflow_id, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (tenant_id, id) DO UPDATE
SET status = EXCLUDED.status,
    workflow_id = EXCLUDED.workflow_id
`

type SaveSignalParams struct {
	ID         string             `json:"id"`
	TenantID   string             `json:"tenant_id"`
	AssetID    string             `json:"asset_id"`
	Symptom    string             `json:"symptom"`
	Status     string             `json:"status"`
	WorkflowID pgtype.Text        `json:"workflow_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) SaveSignal(ctx context.Context, arg SaveSignalParams) error {
	_, err := q.db.Exec(ctx, saveSignal,
		arg.ID,
		arg.TenantID,
		arg.AssetID,
		arg.Symptom,
		arg.Status,
		arg.WorkflowID,
		arg.CreatedAt,
	)
	return err
}
