// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: work_orders.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getWorkOrder = `-- name: GetWorkOrder :one
SELECT id, tenant_id, asset_id, priority, status, idempotency_key, created_at
FROM work_orders
WHERE tenant_id = $1 AND id = $2
`

type GetWorkOrderParams struct {
	TenantID string `json:"tenant_id"`
	ID       string `json:"id"`
}

func (q *Queries) GetWorkOrder(ctx context.Context, arg GetWorkOrderParams) (WorkOrder, error) {
	row := q.db.QueryRow(ctx, getWorkOrder, arg.TenantID, arg.ID)
	var i WorkOrder
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AssetID,
		&i.Priority,
		&i.Status,
		&i.IdempotencyKey,
		&i.CreatedAt,
	)
	return i, err
}

const saveWorkOrder = `-- name: SaveWorkOrder :exec
INSERT INTO work_orders (id, tenant_id, asset_id, priority, status, idempotency_key, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (tenant_id, id) DO UPDATE
SET status = EXCLUDED.status
`

type SaveWorkOrderParams struct {
	ID             string             `json:"id"`
	TenantID       string             `json:"tenant_id"`
	AssetID        string             `json:"asset_id"`
	Priority       string             `json:"priority"`
	Status         string             `json:"status"`
	IdempotencyKey string             `json:"idempotency_key"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) SaveWorkOrder(ctx context.Context, arg SaveWorkOrderParams) error {
	_, err := q.db.Exec(ctx, saveWorkOrder,
		arg.ID,
		arg.TenantID,
		arg.AssetID,
		arg.Priority,
		arg.Status,
		arg.IdempotencyKey,
		arg.CreatedAt,
	)
	return err
}
